### ISSUE TITLE
Inner UnitOfWork Commit issue

### ISSUE THREAD

**Issue by siwicgrey** [riganti/infrastructure#2]
When you call Commit() on inner UOW but last UOW is not commited, the changes are not saved.
There should be some exception thrown, when inner uow gets commited while finally last uow not.

**Comment by luboshl** [comment]
You probably mean `EntityFrameworkUnitOfWork` or `TableStorageUnitOfWork`, where nesting of UoW can be used with reusing of parent `DbContext`. In that case only commit of the most outer UoW saves changes. This behavior is by design and that is purpose of this nesting.

What is important - one must be **very careful when using this nesting of UoW**. For example when I commit inner UoW and expect that I get Id of newly created entity. I don't, unitl the outer UoW is commited. Using of nested UoW is very rare and it is usually better to find a way without nesting of UoW.
